---
env:
  node: true

plugins:
  - import

extends:
  - eslint:recommended
  - plugin:import/recommended
  - prettier

settings:
  import/resolver:
    node: {}

rules:
  # Require all imported dependencies are actually declared in package.json
  "import/no-extraneous-dependencies":
    - error
    - devDependencies: # Only allow importing devDependencies from:
        - "**/test/**" # --> Unit tests
        - "**/utils.js" # --> uses deepmerge
      optionalDependencies: false # Disallow importing optional dependencies (those shouldn"t be in use in the project)
      peerDependencies: false # Disallow importing peer dependencies (that aren"t also direct dependencies)

  # Require all imported libraries actually resolve (!!required for import/no-extraneous-dependencies to work!!)
  "import/no-unresolved":
    - error
